maevsi/sqitch

- .renovaterc
> chore(renovate): remove package rules

- README.md
Add the sqitch logo and instructions on how to run sqitch.
> docs(readme): add run instructions

- schema/schema.definition.sql
- src/deploy/function_authenticate.sql
- src/verify/function_authenticate.sql
Resolves https://github.com/maevsi/maevsi/issues/1510
> feat(authenticate): allow function execution by account role

- schema/schema.definition.sql
- src/deploy/table_report.sql
- src/verify/table_report.sql
Column `created` added to table `maevsi.report`.
> feat(report): add created column

- src/deploy/table_notification.sql
Somebody forgot to remove function notify.
> chore(notification): remove function notify

- schema/schema.definition.sql
- src/deploy/table_notification.sql
First step to full event streaming migration
> feat(notification)!: remove trigger

- schema/schema.definition.sql
- src/deploy/table_account_private.sql
- src/verify/table_account_private.sql
In table maevsi_private.account a new column was added to store the account owner's day of birth.
> feat(account): add day of birth

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
There was a wish for more documentation. Here is some, be encouraged to add to it!
> docs: add contribution guide

- src/verify/function_account_registration.sql
Some more tests on account registration for inspiration.
> test(account): extend for registration

- schema/schema.definition.sql
- src/deploy/enum_language.sql
- src/deploy/table_contact.sql
- src/revert/enum_language.sql
- src/sqitch.plan
- src/verify/enum_language.sql
- src/verify/table_contact.sql
Resolves #7 
Resolves #12 
Resolves #19
> feat(contact): add language, nickname and time zone

- schema/schema.definition.sql
- src/deploy/table_account_preference_event_size.sql
- src/deploy/table_contact.sql
- src/deploy/table_event.sql
- src/deploy/table_event_group.sql
- src/deploy/table_invitation.sql
- src/deploy/table_report.sql
- src/deploy/table_upload.sql
- src/verify/table_account_preference_event_size.sql
- src/verify/table_contact.sql
- src/verify/table_event.sql
- src/verify/table_event_group.sql
- src/verify/table_invitation.sql
- src/verify/table_report.sql
- src/verify/table_upload.sql
Resolves https://github.com/maevsi/sqitch/issues/13
> feat(table): add creation timestamps

- schema/schema.definition.sql
- src/deploy/table_account_preference_event_size.sql
- src/deploy/table_contact.sql
- src/deploy/table_event.sql
- src/deploy/table_event_group.sql
- src/deploy/table_invitation.sql
- src/deploy/table_legal_term_acceptance.sql
- src/deploy/table_upload.sql
> fix: omissions

- README.md
- test/data.patch
Resolves https://github.com/maevsi/sqitch/issues/16
> test(dx): add command to seed data for development

- schema/schema.definition.sql
- src/deploy/table_invitation.sql
- src/deploy/table_invitation_policy.sql
- src/verify/table_invitation.sql
Add `updated_at` and `updated_by` columns to the invitation table.
> feat(invitation): add update metadata

- schema/schema.definition.sql
- src/deploy/function_authenticate.sql
- src/deploy/function_jwt_refresh.sql
- src/deploy/table_account_private.sql
- src/deploy/table_legal_term.sql
- src/deploy/table_legal_term_acceptance.sql
- src/deploy/table_report.sql
Align time zone usage across files.
See #78.
> feat(timestamp)!: add time zone

- src/deploy/role_account.sql
- src/deploy/role_anonymous.sql
- src/deploy/role_grafana.sql
- src/deploy/role_postgraphile.sql
- src/deploy/role_tusd.sql
This helps with the deployment of our current migration strategy.
> fix(role): drop before creation

- src/deploy/table_event_favourite.sql
- src/deploy/table_event_favourite_policy.sql
- src/revert/table_event_favourite.sql
- src/revert/table_event_favourite_policy.sql
- src/sqitch.plan
- src/verify/table_event_favourite.sql
- src/verify/table_event_favourite_policy.sql
- test/schema/schema.definition.sql
> feat(event): mark events as favourite

- src/deploy/enum_achievement_type.sql
- test/schema/schema.definition.sql
There is now a new achievement type `early_bird`.
> feat(achievement): add early bird achievement

- src/deploy/function_invoker_account_id.sql
- src/sqitch.plan
- src/verify/function_invoker_account_id.sql
- test/schema/schema.definition.sql
There was a missing permission for the upload service to access a newly introduced database function that I think made the upload creation fail for you. This PR should fix the issue.
> fix(invoker-account-id): grant execute for tusd

- src/deploy/extension_pgcrypto.sql
- src/deploy/extension_postgis.sql
- src/deploy/function_account_delete.sql
- src/deploy/function_account_password_change.sql
- src/deploy/function_account_password_reset.sql
- src/deploy/function_account_registration.sql
- src/deploy/function_authenticate.sql
- src/deploy/function_event_delete.sql
- src/verify/extension_pgcrypto.sql
- src/verify/extension_postgis.sql
- test/schema/schema.definition.sql
Apparently, schema `public` works too.
> refactor(extension): use schema public

- src/deploy/function_account_delete.sql
- src/deploy/function_account_password_change.sql
- src/deploy/function_account_password_reset.sql
- src/deploy/function_account_registration.sql
- src/deploy/function_authenticate.sql
- src/deploy/function_event_delete.sql
- src/verify/extension_pgcrypto.sql
- test/schema/schema.definition.sql
> refactor(schema): remove prefix `public`

- CONTRIBUTING.md
- Dockerfile
Explain the edge case in development in which the CI's PostgreSQL container image is more up to date than the image used by the developer and how to handle that situation.
cc @Bobomify if interested, see the standardized `.md` files in the repositories that we're already using for project-specific documentation
> docs(contributing): explain debezium's postgres image edge case

- CONTRIBUTING.md
- Dockerfile
- src/deploy/table_contact.sql
- src/deploy/table_event.sql
- src/deploy/view_guest_flat.sql
- src/verify/table_contact.sql
- src/verify/table_event.sql
- src/verify/view_guest_flat.sql
- test/schema/schema.definition.sql
Resolves the retrospective feedback by @sthelemann on #134.
> feat(address)!: correct reference columns' name suffix

- Dockerfile
- src/deploy/table_account_block.sql
- src/deploy/table_address.sql
- src/deploy/table_event.sql
- src/deploy/table_event_group.sql
- src/deploy/table_event_grouping.sql
- src/deploy/table_guest.sql
- src/revert/table_address.sql
- src/revert/table_event.sql
- src/revert/table_event_group.sql
- src/revert/table_event_grouping.sql
- src/revert/table_guest.sql
- src/sqitch.plan
- src/verify/table_account_block.sql
- src/verify/table_address.sql
- src/verify/table_event.sql
- src/verify/table_event_group.sql
- src/verify/table_event_grouping.sql
- src/verify/table_guest.sql
- test/index-missing.sql
- test/schema/schema.definition.sql
> perf(index): correct amount

- Dockerfile
- src/sqitch
Forgot to remove some lines in 960b97899d8b55cd1b1ef9aad9065c4b1b7f9118.
> chore(grafana): remove leftovers

- src/deploy/table_address_policy.sql
- src/deploy/table_friendship_policy.sql
As suggested in https://github.com/maevsi/sqitch/pull/157#pullrequestreview-2688349250.
> chore(policy): explicitly target all

- CHANGELOG.md
- package.json
- src/deploy/table_event_format.sql
- src/deploy/table_event_format_mapping.sql
- src/revert/table_event_format.sql
- src/revert/table_event_format_mapping.sql
- src/sqitch.plan
- src/verify/table_event_format.sql
- src/verify/table_event_format_mapping.sql
- test/schema/schema.definition.sql
We need this in order to continue working on the event format topic.
> chore: merge main into beta

- src/verify/function_authenticate.sql
- src/verify/test_location.sql
Use our helper function to shorten duplicate implementations.
> refactor(test): use verified account registration helper

- src/deploy/table_event_favorite.sql
- test/fixture/schema.definition.sql
It should be possible to set `created_by` at creation.
cc @huzaifaedhi22
> fix(event-favorite)!: correct smart tags

- docs/onboarding/project.md
- test/data.patch
> docs(project): simplify test data update instructions

- docs/onboarding/database/roles.md
- src/revert/role_postgraphile.sql
- src/revert/role_vibetype.sql
- src/verify/table_event_format.sql
- src/verify/table_event_format_mapping.sql
Cleaning up some leftovers from our recent change to role naming.
> chore: clean up roles

- src/deploy/table_event_category.sql
- src/deploy/table_event_format.sql
- test/fixture/schema.definition.sql
No need to expose api endpoints that are unavailable due to missing `GRANT`s.
> feat(event)!: disable endpoints for category and format

- src/deploy/function_account_birth_date_update.sql
- src/revert/function_account_birth_date_update.sql
- src/sqitch.plan
- src/verify/function_account_birth_date_update.sql
- test/fixture/schema.definition.sql
As the birth date is private, we need a setter function with `SECURITY DEFINER`.
> feat(account): add birth date setter function

- src/deploy/table_event_favorite.sql
- test/fixture/schema.definition.sql
> fix(event)!: disallow null id for favorite

- Dockerfile
- src/deploy/database_zammad.sql
- src/deploy/role_zammad.sql
- src/revert/database_zammad.sql
- src/revert/role_zammad.sql
- src/sqitch
- src/sqitch.plan
- src/verify/database_zammad.sql
- src/verify/role_zammad.sql
Scripts for creating a database and login role `zammad` have been created.
> feat(zammad): create database and role

- src/deploy/table_preference_event_size.sql
- test/fixture/schema.definition.sql
I think these shouldn't be `null`able.
> fix(preference)!: disallow columns to be null for size

- src/deploy/function_account_password_reset_request.sql
- src/deploy/function_account_registration_refresh.sql
- src/deploy/function_event_unlock.sql
- src/deploy/function_invite.sql
- src/deploy/function_jwt_refresh.sql
- test/development/data.patch
- test/fixture/schema.definition.sql
INTO clauses in queries now all follow immediately after the SELECT clause.
> refactor!: reposition `INTO` clauses

- src/deploy/function_account_delete.sql
- src/deploy/function_account_email_address_verification.sql
- src/deploy/function_account_location_update.sql
- src/deploy/function_account_password_change.sql
- src/deploy/function_account_password_reset.sql
- src/deploy/function_account_registration_refresh.sql
- src/deploy/function_achievement_unlock.sql
- src/deploy/function_audit_log.sql
- src/deploy/function_authenticate.sql
- src/deploy/function_event_delete.sql
- src/deploy/function_event_unlock.sql
- src/deploy/function_invite.sql
- src/deploy/function_notification_acknowledge.sql
- test/fixture/schema.definition.sql
For each function that can may raise an exception, the error codes are documented in the comment of the function.
> docs!: document function error codes

- src/deploy/2025-07-09_account_block_delete.sql
- src/revert/2025-07-09_account_block_delete.sql
- src/sqitch.plan
- src/verify/2025-07-09_account_block_delete.sql
- test/fixture/schema.definition.sql
@huzaifaedhi22 is already working on the unblocking ui and needs this updated policy permission.
> feat(account): allow unblock

- src/deploy/2025-07-20_device_policy_service.sql
- src/revert/2025-07-20_device_policy_service.sql
- src/sqitch.plan
- src/verify/2025-07-20_device_policy_service.sql
- test/fixture/schema.definition.sql
- test/fixture/schema_vibetype.definition.sql
Non-breaking variant of https://github.com/maevsi/sqitch/pull/238 by @myyxl
> feat(device): add access control for service account
