maevsi/sqitch

- schema/schema.definition.sql
- src/deploy/enum_invitation_feedback_paper.sql
As given a few lines above, `none` is also valid, but was not part of the description yet.
> docs(invitation-feedback): add `none`

- schema/schema.definition.sql
- src/deploy/table_contact_policy.sql
`NULL` is always not inequal to anything. So instead of `!=` or `<>` we need to check if `IS DISTINCT FROM`.
> fix(contact): account for null in inequality check

- schema/schema.definition.sql
- src/deploy/table_report.sql
It's prohibited to update or delete reports, so we should not offer such endpoints via the graphql api as they'd fail in all cases.
> fix(report): correct smart tags

- schema/schema.definition.sql
- src/deploy/table_account_private.sql
- src/verify/function_account_registration.sql
I've
- extended the `function_account_registration` test so that exceptions can be pinpointed to a certain line better
- added a function invocation test
- wrapped the tests with a savepoint + rollback, for which the savepoint's variable name conveniently acts as the test name
> test(account): registration

- schema/schema.definition.sql
- src/deploy/function_account_registration.sql
I've replaced function variable ids with names which improve code readability. I use the prefixed function name to be able to keep the variable names and therefore not break the GraphQL api.
> refactor(account): use function variable names in registration

- schema/schema.definition.sql
- src/deploy/table_account_private.sql
- src/verify/table_account_private.sql
Align column name to column names in other tables.
I've created a `beta` branch for this breaking change and more to come.
See #78.
> feat(account)!: rename `created` column to `created_at`

- schema/schema.definition.sql
- src/deploy/function_account_email_address_verification.sql
- src/deploy/function_account_password_reset.sql
- src/deploy/function_account_registration.sql
- src/deploy/function_authenticate.sql
- src/deploy/function_jwt_refresh.sql
- src/deploy/table_account_private.sql
- src/deploy/table_notification.sql
`CURRENT_TIMESTAMP` should be standard SQL, `NOW` a PostgreSQL-specific alias. Let's use the standardized variant as discussed.
> refactor: use standardized timestamp notation

- schema/schema.definition.sql
- src/deploy/table_event_upload.sql
- src/deploy/table_event_upload_policy.sql
- src/deploy/table_upload.sql
- src/revert/table_event_upload.sql
- src/revert/table_event_upload_policy.sql
- src/sqitch.plan
- src/verify/table_event_upload.sql
- src/verify/table_event_upload_policy.sql
- src/verify/table_upload.sql
A new table event_upload is introduced to store the connection between uploaded images and events. If more than one image is assigned to an event the sorting of these images  will be based on the image file name. To enable this, file_name is now an additional column in the table upload. This table has another new column, file_type, with the default value 'image' as currently only image files can be uploaded.
> feat(event): assign images to events

- Dockerfile
Our stack is using Debezium's PostgreSQL image for change data capture since https://github.com/maevsi/maevsi_stack/pull/141. This PR aligns the PostgreSQL image in this repository.
The sqitch version available in Debezium's image is older and Debian's testing `apt` source needs to be removed to prevent a conflict with system libraries, but the output remains the same.
> chore(docker): use debezium postgres image for testing

- src/deploy/extension_postgis.sql
- src/revert/extension_postgis.sql
- src/sqitch.plan
- src/verify/extension_postgis.sql
- test/schema/schema.definition.sql
Here we go, enabling PostGIS support for maevsi's database. It appears that PostGIS functions and tables are not shown in Postgraphile. This is a breaking change as it requires the Debezium PostgreSQL container version in `maevsi_stack` to change to the non-alpine variant which has PostGIS bundled.
> feat(extension)!: add postgis

- src/deploy/enum_event_visibility.sql
- test/schema/schema.definition.sql
The enum type `event.visibility` now has the additional value `unlisted`.
> feat(event)!: add visibility unlisted

- .github/workflows/ci.yml
Right now there are no new beta releases created because there is already a PR for merging the `beta` branch into `master` and the optimization job skips workflow runs in that case. I think filtering out draft PRs would be a plausible fix.
> ci: filter out drafts from job optimization

- src/deploy/schema_test.sql
- src/deploy/test_location.sql
- src/revert/test_location.sql
- src/verify/schema_public.sql
- src/verify/schema_test.sql
- src/verify/test_location.sql
- test/schema/schema.definition.sql
If some of there functions will be used as a feature eventually, they can get dragged back out of the test schema again. I just don't want to inflate the api surface with endpoints that are not actually in use besides testing.
> fix(location): move test function to appropriate schema

- src/deploy/function_account_block_ids.sql
- src/deploy/function_invitation_claim_array.sql
- test/schema/schema.definition.sql
Function `invitation_claim_array` now has call mode SECURITY DEFINER. The function's implementation was updated, too.
> fix(account-block): change function call mode to SECURITY DEFINER

- src/deploy/table_event.sql
- test/schema/schema.definition.sql
Based on your [comment](https://github.com/maevsi/sqitch/pull/121/files#r1929843799), @sthelemann, I removed the `coalesce` for `name` and also added an early return if no column is changed that would result in an update on the search vector.
> perf(event): early return search trigger function

- src/deploy/function_account_delete.sql
- src/deploy/function_account_email_address_verification.sql
- src/deploy/function_account_password_change.sql
- src/deploy/function_account_password_reset.sql
- src/deploy/function_account_password_reset_request.sql
- src/deploy/function_account_registration.sql
- src/deploy/function_account_registration_refresh.sql
- src/deploy/function_achievement_unlock.sql
- src/deploy/function_event_delete.sql
- src/deploy/function_event_guest_count_maximum.sql
- src/deploy/function_event_is_existing.sql
- src/deploy/function_event_unlock.sql
- src/deploy/function_guest_count.sql
- src/deploy/function_invite.sql
- src/deploy/function_jwt_refresh.sql
- src/deploy/function_notification_acknowledge.sql
- src/deploy/function_profile_picture_set.sql
- src/deploy/function_upload_create.sql
- test/schema/schema.definition.sql
Instead of `$1` and `$2`, we use `function.parameter` syntax everywhere now.
> refactor(function): use parameter names

- src/deploy/test_account_block.sql
Developers should notice if a function is created more than once. Such duplication is likely unintended.
It can result in extensive time for debugging to find the source for ambiguity.
I know using the replace may help while creating tests, but I'd say it must not necessarily be committed.
> test(account-block): prevent possibility for function replacement

- src/deploy/table_address_policy.sql
- src/revert/table_address_policy.sql
- test/schema/schema.definition.sql
I propose to collapse the policy statements for `address` into one.
> feat(address): simplify policies

- Dockerfile
- src/deploy/schema_test.sql
- src/deploy/test_account_blocking.sql
- src/revert/test_account_blocking.sql
- test/schema/schema.definition.sql
The superuser username should stay flexible to allow for a different username in production. This PR customizes the CI's superuser username so that it's obvious that it's not meant to be hardcoded in the migrations.
> test(ci): customize superuser name

- Dockerfile
- README.md
- docker-entrypoint.sh
- src/SQITCH_TARGET.env
- src/sqitch
- src/sqitch.conf
Instead of conditional value sourcing, set the correct target specific to the environment.
This allows to connect via port `5432` instead of mounting the socket. The socket would be more private, but overriding host files can lead to some confusion as it also mounts secret files to the host. Other services are exposed via the network too, we may need some general review of the security logic for development here eventually.
Migration guide:
- expose postgres port `5432` for development
cc @HMDank
> refactor(environment)!: dissolve target variable file

- src/sqitch
@maevsi/contributors-active this change expects the stack directory to be named `stack` instead of `vibetype_stack`. If you're running `sqitch deploy` in your CLI with this commit applied, the directory name must match, if you're just running sqitch inside the stack, you can continue as usual.
> chore(stack): shorten name

- src/deploy/table_event_format.sql
- src/deploy/table_event_format_mapping.sql
- src/revert/table_event_format.sql
- src/revert/table_event_format_mapping.sql
- src/sqitch.plan
- src/verify/table_event_format.sql
- src/verify/table_event_format_mapping.sql
- test/schema/schema.definition.sql
In addition to an event category (like "arts") there should be an event format (like "lecture"). This PR adds the required mapping.
TODO: extend the `account_interest` concept so that accounts can show their interests in event formats as well. @sthelemann could you take this over? I'd propose to rename `account_interest` to `account_preference_event_category` (as we already have `account_preference_event_size` following this naming scheme) and create a new `account_preference_event_format` in a separate PR basing off of `beta`.
> feat(event): add format mapping

- src/deploy/table_account_block.sql
- src/deploy/table_account_preference_event_size.sql
- src/deploy/table_achievement.sql
- src/deploy/table_address.sql
- src/deploy/table_contact.sql
- src/deploy/table_device.sql
- src/deploy/table_event.sql
- src/deploy/table_event_favorite.sql
- src/deploy/table_event_group.sql
- src/deploy/table_event_grouping.sql
- src/deploy/table_event_upload.sql
- src/deploy/table_friendship.sql
- src/deploy/table_guest.sql
- src/deploy/table_profile_picture.sql
- src/deploy/table_report.sql
- src/deploy/table_upload.sql
- src/verify/test_postgres.sql
- test/schema/schema.definition.sql
Many foreign key constrains did not have an `ON DELETE referential_action`clause. In many cases `ON DELETE CASCADE` was added, in a few cases `ON DELETE SET NULL`.
Waiting for:
- https://github.com/maevsi/sqitch/pull/168
> feat(constraint)!: add `ON DELETE` clauses to foreign keys

- src/deploy/function_account_email_address_verification.sql
- src/deploy/function_account_registration.sql
- src/verify/function_account_registration.sql
- test/schema/schema.definition.sql
We can't tell about the existence of email addresses within our system.
cc @sthelemann
> feat(account)!: fail silently at registration on duplicate email

- src/deploy/table_account_public.sql
- src/verify/table_account_public.sql
- test/schema/schema.definition.sql
Two columns were added to table `vibetype.account`: `imprint` and `description`.
> feat(account)!: add imprint and description

- README.md
- docs/onboarding/project.md
- package.json
- src/sqitch
No need to use `nypm` in all cases. This PR also makes the sqitch script ask for a sudo password automatically now if required.
> docs(project): simplify scripts

- Dockerfile
- src/deploy/database_grafana.sql
- src/deploy/role_grafana.sql
- src/deploy/schema_private.sql
- src/deploy/table_account_private.sql
- src/revert/database_grafana.sql
- src/revert/role_grafana.sql
- src/sqitch
- src/sqitch.plan
- src/verify/database_grafana.sql
- src/verify/role_grafana.sql
- test/fixture/schema.definition.sql
We had the Grafana integration here before but it has been removed due to some logical inaccuracies back then (https://github.com/maevsi/sqitch/pull/107). This PR readds the Grafana database and role so that it configures access permissions properly right away, meaning you can just start `maevsi/stack` and have working dashboard in the `grafana` service.
Test with https://github.com/maevsi/stack/pull/200 (which targets `beta` too).
> feat(grafana)!: readd

- src/revert/table_account_private.sql
- src/revert/table_contact.sql
- src/revert/table_device.sql
- src/revert/table_event_policy.sql
- src/revert/table_guest_policy.sql
- src/revert/table_legal_term.sql
Unifies the syntax for `DROP FUNCTION` statements.
> chore!: specify function arguments for revert

- src/deploy/table_account_block.sql
- src/deploy/table_legal_term_acceptance.sql
- test/fixture/schema.definition.sql
> fix!: add missing smart comment prefix

- src/deploy/table_preference_event_category.sql
- src/deploy/table_preference_event_format.sql
- src/deploy/table_preference_event_size.sql
- src/verify/table_preference_event_category.sql
- src/verify/table_preference_event_format.sql
- src/verify/table_preference_event_size.sql
- test/fixture/schema.definition.sql
Adds an `id` column to the preference tables which currently have a composite primary key. This helps reduce some frontend complexity, see https://nearform.com/open-source/urql/docs/graphcache/.
> feat(preference)!: add id

- .husky/commit-msg
Husky uses sh and does not source files like `.bashrc` or `.zshrc`. As the development instructions for maevsi instruct to use nvm, we can work around the "Node / pnpm not found" error in GUI applications like GitKraken by sourcing the nvm initializer in the Git hooks, I think.
User-based configurations would require additional setup instructions which a developer should not need to care about imo. Of course this change expects the nvm initialization script to be at in a specific place, but I think we can assume that this standard path is the same on all developers' machines for now.
> chore(git): initialize `nvm` in hook

- src/deploy/2025-06-13_event_favorite_anonymous.sql
- src/revert/2025-06-13_event_favorite_anonymous.sql
- src/sqitch.plan
- src/verify/2025-06-13_event_favorite_anonymous.sql
- test/fixture/schema.definition.sql
- test/logic/main.sql
- test/logic/scenario/model/event_favorite.sql
While developing the frontend I noticed that it would noticeably reduce frontend code complexity and package size if we allowed anonymous users to query tables that we don't expect to return any data to them. Of course this increases load on the database somewhat but spammers should be taken care of by our session logic before too many requests hit the database and the load increase should be acceptable for us compared to the increase in package size and code complexity with the current configuration.
Also, I wrote this change as an incremental migration for the first time so that it is not breaking. I expect to merge all incremental changes back into our existing files from time to time when the amount of changes accumulated make sense to do so. This time I'll submit the matching beta …
> feat(event-favorite): grant select for anonymous

- src/deploy/2025-07-04_account_public_username_collate.sql
- src/revert/2025-07-04_account_public_username_collate.sql
- src/sqitch.plan
- src/verify/2025-07-04_account_public_username_collate.sql
- test/fixture/schema.definition.sql
User search would benefit from ordered results like
- name
- Name
- user
- User
instead of
- Name
- User
- name
- user
so Unicode collation is added to the username column of the account table.
> feat(account): specify unicode collation for username

- src/deploy/2025-07-06_account_public_policy_block.sql
- src/revert/2025-07-06_account_public_policy_block.sql
- src/sqitch.plan
- src/verify/2025-07-06_account_public_policy_block.sql
- test/fixture/schema.definition.sql
After blocking an account, the account should not appear in the list of accounts anymore / the account profile should not be shown in the UI anymore.
> fix(account): disallow selecting blocked

- .github/workflows/ci.yml
- .github/workflows/release-schedule.yml
It's recommended to specify the least needed permissions for all workflow jobs, so here we go with `contents: read`. If more are needed, the pipeline will surely complain.
> ci: set read permissions
